# Generated by Django 5.0 on 2023-12-26 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('image', models.ImageField(default='name', upload_to='media')),
                ('slug', models.CharField(max_length=500, unique=True)),
                ('vehicle_description', models.TextField()),
                ('vehicle_specification', models.TextField()),
                ('price_per_day', models.IntegerField()),
                ('Company_name', models.CharField(max_length=300)),
                ('Company_contact', models.CharField(max_length=300)),
                ('Vehicle_number', models.CharField(max_length=300)),
                ('color', models.CharField(max_length=300)),
                ('mileage', models.IntegerField()),
                ('engine_type', models.CharField(choices=[('petrol', 'Petrol'), ('Diesel', 'Diesel'), ('electric', 'Electric')], max_length=10)),
                ('TermsCondition1', models.TextField()),
                ('TermsCondition2', models.TextField()),
                ('TermsCondition3', models.TextField()),
                ('TermsCondition4', models.TextField()),
                ('TermsCondition5', models.TextField(blank=True)),
                ('TermsCondition6', models.TextField(blank=True)),
                ('TermsCondition7', models.TextField(blank=True)),
                ('stock', models.CharField(choices=[('in_stock', 'In Stock'), ('out of stock', 'Out of Stock')], max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.category')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.type')),
            ],
        ),
    ]
