# Generated by Django 5.0 on 2024-01-04 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_type_description_alter_vehicle_termscondition1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='vehicle_description1',
            new_name='vehicle_description',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='vehicle_description2',
            new_name='vehicle_specification',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_description3',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_description4',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_specification1',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_specification2',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_specification3',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_specification4',
        ),
    ]
