# Generated by Django 5.0 on 2024-01-04 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_vehicle_description1_vehicle_vehicle_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='TermsCondition5',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='TermsCondition6',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='TermsCondition7',
            field=models.TextField(max_length=200),
        ),
    ]
