# Generated by Django 5.0 on 2024-01-04 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_vehicle_termscondition5_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('slug', models.CharField(max_length=500, unique=True)),
                ('First_name', models.CharField(max_length=300)),
                ('Last_name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('Phone', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=300)),
                ('tole_name', models.CharField(max_length=300)),
                ('Address', models.CharField(max_length=300)),
                ('street', models.CharField(max_length=300)),
                ('House_number', models.CharField(blank=True, max_length=300)),
                ('Vehicle_name', models.CharField(max_length=300)),
                ('Star_date', models.DateField()),
                ('total_days', models.IntegerField()),
                ('cost_per_day', models.IntegerField()),
                ('total_cost', models.IntegerField()),
                ('vehicle_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.vehicle')),
            ],
        ),
    ]
