# Generated by Django 5.0 on 2024-01-04 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_checkout'),
    ]

    operations = [
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=300)),
                ('Last_name', models.CharField(max_length=300)),
                ('Email', models.EmailField(max_length=254)),
                ('Company_name', models.CharField(max_length=300)),
                ('Username', models.CharField(max_length=300)),
                ('Password', models.CharField(max_length=300)),
                ('Company_document', models.ImageField(upload_to='media')),
                ('Citizenship_document', models.ImageField(upload_to='media')),
                ('slug', models.CharField(max_length=500, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='checkout',
            name='conformation',
            field=models.BooleanField(default=False),
        ),
    ]
