# Generated by Django 5.0 on 2024-01-08 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_staff_checkout_conformation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='slug',
        ),
    ]
