# Generated by Django 5.0 on 2024-01-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_staff_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='Citizenship_document',
            field=models.ImageField(upload_to='media/citizenship/'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='Company_document',
            field=models.ImageField(upload_to='media/documents/'),
        ),
    ]
