# Generated by Django 5.0 on 2024-01-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_staff_citizenship_document_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=300)),
                ('star', models.IntegerField()),
                ('slug', models.CharField(max_length=300)),
                ('review', models.TextField(max_length=600)),
            ],
        ),
    ]
