# Generated by Django 5.0 on 2024-01-09 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_review_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='review',
            new_name='User_review',
        ),
    ]
