# Generated by Django 5.0 on 2024-01-10 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_rename_review_user_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_review',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
