# Generated by Django 5.0 on 2024-01-10 05:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_user_review_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_review',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
