# Generated by Django 5.0.2 on 2024-03-10 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_user_review_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='First_name',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='Last_name',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='Password',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='Username',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='TermsCondition2',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='TermsCondition3',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='TermsCondition4',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='TermsCondition5',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='TermsCondition6',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='TermsCondition7',
        ),
        migrations.AddField(
            model_name='staff',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='bulkbidding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Phone', models.CharField(max_length=300)),
                ('requirements', models.TextField(max_length=200)),
                ('date', models.DateField()),
                ('is_accepted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_accepted', models.BooleanField(default=False)),
                ('bid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bid_comments', to='home.bulkbidding')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
