# Generated by Django 5.0.2 on 2024-04-01 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_remove_staff_email_remove_staff_first_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='conformation',
            new_name='is_ordered',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='First_name',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='House_number',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='Last_name',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='Star_date',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='Vehicle_name',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='city',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='cost_per_day',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='email',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='street',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='tole_name',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='total_cost',
        ),
        migrations.AddField(
            model_name='checkout',
            name='Start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Booking_User', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='Address',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='Phone',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='name',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='total_days',
            field=models.IntegerField(null=True),
        ),
    ]
