# Generated by Django 5.0.2 on 2024-04-10 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_rename_conformation_checkout_is_ordered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='is_completed',
            field=models.BooleanField(default=True),
        ),
    ]
